### ISSUE TITLE
place Annex-Docs

### ISSUE THREAD

**Issue by juexiao12** [ehah/Hybrid-Annex#1]
How do I place Annex-Docs to make them useful in osate?
![image](https://github.com/ehah/Hybrid-Annex/assets/88312313/db703e47-dd79-409c-8c2f-49adfbad80d3)

**Comment by ehah** [comment]
You need to create an OSATE plugin.

**Comment by juexiao12** [comment]
> 您需要创建一个 OSATE 插件。
按照您的建议，我在菜单栏中的help->install New software 中下载了Hybrid-Annex。
但当我打开Window->preference后出现这样的错误。
![image](https://github.com/ehah/Hybrid-Annex/assets/88312313/88ddc1a7-4ea3-4874-bace-2d3f446714f9)
这是正常现象吗？

**Comment by juexiao12** [comment]
> 您需要创建一个 OSATE 插件。

Following your advice, I downloaded the Hybrid-Annex from help->install New software in the menu bar.
But when I open Window->preference I get this error.
! [image](https://github.com/ehah/Hybrid-Annex/assets/88312313/88ddc1a7-4ea3-4874-bace-2d3f446714f9)
Is this normal?

**Comment by juexiao12** [comment]
> You need to create an OSATE plugin.

Following your advice, I downloaded the Hybrid-Annex from help->install New software in the menu bar.
But when I open Window->preference I get this error.
![image](https://github.com/ehah/Hybrid-Annex/assets/88312313/a80fed87-0a86-4020-9542-7e856a250fb6)
Is this normal?

**Comment by juexiao12** [comment]
![image](https://github.com/ehah/Hybrid-Annex/assets/88312313/d4e43a4b-e4d0-44c1-98c5-8c009ee9a45d)
Not the same as behavior annex.
the Reserved Words in Hybrid-Annex do not change color and The code inside the Hybrid-Annex doesn't throw  error .
Is it because of the problem of Hybrid-Annex itself or I downloaded it incorrectly?

**Comment by ehah** [comment]
No. Hybrid annex plugin is under development for current OSATE version. Importing simple textual grammar will not work.
